### ISSUE TITLE
How to set weather?

### ISSUE THREAD

**Issue by mrsamsami** [OATML/carsuite#10]
I can't find any code setting weather conditions.
Is there any way to collect demonstrations with specific weather parameters?

**Comment by filangelos** [comment]
Hey @mrsamsami, right now we are hardcoding the weather conditions [here](https://github.com/OATML/oatomobile/blob/alpha/oatomobile/utils/carla.py#L106), you can modify this line of code as needed.

**Comment by mrsamsami** [comment]
Thanks @filangel :)
