### ISSUE TITLE
Use camera images instead of LiDAR

### ISSUE THREAD

**Issue by mrsamsami** [OATML/carsuite#14]
Hi,
Is there any way to collect camera images instead of LiDAR, and train perception module with them?

**Comment by filangelos** [comment]
Hi @mrsamsami, I suggest you take a look at [this reply](https://github.com/OATML/oatomobile/issues/5#issuecomment-682428842) for collecting the data. As far as training a model on them goes, you would need to do adaptations to the existing models.

**Comment by mrsamsami** [comment]
Thank you @filangel. So in order to collect observations with camera images, should I add `front_camera_rgb` to the `sensors` list?

**Comment by filangelos** [comment]
You should add one/all/combination of the options below to the `sensors` list:
- [`front_camera_rgb`](https://github.com/OATML/oatomobile/blob/alpha/oatomobile/simulators/carla/simulator.py#L211) for first-person view;
- [`rear_camera_rgb`](https://github.com/OATML/oatomobile/blob/alpha/oatomobile/simulators/carla/simulator.py#L233) for rear view;
- [`left_camera_rgb`](https://github.com/OATML/oatomobile/blob/alpha/oatomobile/simulators/carla/simulator.py#L255) for left view;
- [`right_camera_rgb`](https://github.com/OATML/oatomobile/blob/alpha/oatomobile/simulators/carla/simulator.py#L277) for right view.
