### ISSUE TITLE
gym.make interface

### ISSUE THREAD

**Issue by bionicles** [OATML/carsuite#2]
this looks cool, and i want to use it, but there's no list of environment names, and it appears to use a custom function to make the environments ... would it be possible to use gym.make for this? we make hundreds of environments in a loop. it's ideal if they all work the same way:

`env = gym.make(name)`

if this project **must** use a custom way to make the environments, then where is the list of possible environments we can use? then we can do, `env = make_carsuite(name) if name in CARSUITE_NAMES else gym.make(name)`

**Comment by filangelos** [comment]
We plan to set up `gym` registration, for now, you can find the list of environments by running:

```python
>>> import carsuite
>>> list(carsuite.carnovel.tasks.keys())
['BusyTown2-v0',
 'BusyTown0-v0',
 'BusyTown4-v0',
 'Roundabouts3-v0',
 'BusyTown8-v0',
 'Roundabouts1-v0',
 'AbnormalTurns4-v0',
 'Hills3-v0',
 'BusyTown5-v0',
 'AbnormalTurns0-v0',
 'BusyTown9-v0',
 'AbnormalTurns3-v0',
 'AbnormalTurns1-v0',
 'BusyTown3-v0',
 'AbnormalTurns2-v0',
 'Hills0-v0',
 'BusyTown7-v0',
 'Roundabouts0-v0',
 'AbnormalTurns5-v0',
 'BusyTown1-v0',
 'Roundabouts4-v0',
 'BusyTown6-v0',
 'Hills1-v0',
 'BusyTown10-v0',
 'AbnormalTurns6-v0',
 'Hills2-v0',
 'Roundabouts2-v0']
```

and you can load the environment using:

```python
>>> env = carsuite.carnovel.load("BusyTown2-v0")
```
